<?php
/* Generated by bilingual installer */

if (!function_exists('ensure_session_started')) {
  function ensure_session_started() {
    if (session_status() === PHP_SESSION_NONE) {
      @session_start();
    }
  }
}

if (!function_exists('current_lang')) {
  function current_lang() {
    ensure_session_started();

    $allowed = array('fa', 'en');

    if (isset($_GET['lang']) && in_array($_GET['lang'], $allowed, true)) {
      $_SESSION['site_lang'] = $_GET['lang'];
      return $_GET['lang'];
    }

    if (!empty($_SESSION['site_lang']) && in_array($_SESSION['site_lang'], $allowed, true)) {
      return $_SESSION['site_lang'];
    }

    return 'fa';
  }
}

if (!function_exists('is_fa')) {
  function is_fa() {
    return current_lang() === 'fa';
  }
}

if (!function_exists('is_en')) {
  function is_en() {
    return current_lang() === 'en';
  }
}

if (!function_exists('page_dir')) {
  function page_dir() {
    return is_en() ? 'ltr' : 'rtl';
  }
}

if (!function_exists('page_lang_attr')) {
  function page_lang_attr() {
    return is_en() ? 'en' : 'fa';
  }
}

if (!function_exists('locale_code')) {
  function locale_code() {
    return is_en() ? 'en_US' : 'fa_IR';
  }
}

if (!function_exists('switch_lang_url')) {
  function switch_lang_url($lang) {
    $lang = ($lang === 'en') ? 'en' : 'fa';

    $uri = isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '';
    if ($uri === '') {
      return BASE_URL . '/?lang=' . $lang;
    }

    $parts = parse_url($uri);
    $path  = isset($parts['path']) ? $parts['path'] : '';
    $query = array();

    if (!empty($parts['query'])) {
      parse_str($parts['query'], $query);
    }

    $query['lang'] = $lang;
    $qs = http_build_query($query);

    return $path . ($qs ? ('?' . $qs) : '');
  }
}

if (!function_exists('append_lang_to_url')) {
  function append_lang_to_url($url) {
    $sep = (strpos($url, '?') !== false) ? '&' : '?';
    return $url . $sep . 'lang=' . current_lang();
  }
}

if (!function_exists('localized_field')) {
  function localized_field($row, $faField, $enField = null) {
    if (!is_array($row)) return '';

    $enField = $enField ?: ($faField . '_en');

    if (is_en() && isset($row[$enField]) && trim((string)$row[$enField]) !== '') {
      return $row[$enField];
    }

    return isset($row[$faField]) ? $row[$faField] : '';
  }
}

if (!function_exists('detect_text_lang')) {
  function detect_text_lang($text) {
    $text = trim((string)$text);
    if ($text === '') return 'fa';

    return preg_match('/[\x{0600}-\x{06FF}]/u', $text) ? 'fa' : 'en';
  }
}

if (!function_exists('translate_text')) {
  function translate_text($text, $from, $to) {
    $text = trim((string)$text);
    $from = ($from === 'en') ? 'en' : 'fa';
    $to   = ($to === 'en') ? 'en' : 'fa';

    if ($text === '' || $from === $to) return $text;

    static $mapFaEn = array(
      'خدمات' => 'Services',
      'املاک' => 'Real Estate',
      'خودرو' => 'Cars',
      'استخدام' => 'Jobs',
      'راهنما' => 'Help',
      'درباره ما' => 'About Us',
      'نیازمندی‌ها' => 'Classifieds',
      'ثبت آگهی' => 'Post Ad',
      'جستجو' => 'Search',
    );

    static $mapEnFa = array(
      'Services' => 'خدمات',
      'Real Estate' => 'املاک',
      'Cars' => 'خودرو',
      'Jobs' => 'استخدام',
      'Help' => 'راهنما',
      'About Us' => 'درباره ما',
      'Classifieds' => 'نیازمندی‌ها',
      'Post Ad' => 'ثبت آگهی',
      'Search' => 'جستجو',
    );

    if ($from === 'fa' && $to === 'en' && isset($mapFaEn[$text])) return $mapFaEn[$text];
    if ($from === 'en' && $to === 'fa' && isset($mapEnFa[$text])) return $mapEnFa[$text];

    return $text;
  }
}

if (!function_exists('t')) {
  function t($key) {
    static $dict = array(
      'fa' => array(
        'site_name' => 'نیازمندی‌ها',
        'home' => 'خانه',
        'search' => 'جستجو',
        'search_placeholder' => 'جستجو در آگهی‌ها…',
        'post_ad' => 'ثبت آگهی',
        'about' => 'درباره ما',
        'help' => 'راهنما',
        'login' => 'ورود',
        'logout' => 'خروج',
        'register' => 'ثبت‌نام',
        'my_listings' => 'آگهی‌های من',
        'admin' => 'مدیریت',
        'settings' => 'تنظیمات',
        'choose_category' => 'انتخاب کنید…',
        'city_optional' => 'شهر (اختیاری)',
        'listing_title' => 'عنوان آگهی',
        'listing_body' => 'متن آگهی',
        'submit_for_review' => 'ثبت برای تایید',
        'image_1_optional' => 'تصویر ۱ (اختیاری)',
        'image_2_optional' => 'تصویر ۲ (اختیاری)',
        'nothing_found' => 'چیزی پیدا نشد.',
      ),
      'en' => array(
        'site_name' => 'Classifieds',
        'home' => 'Home',
        'search' => 'Search',
        'search_placeholder' => 'Search listings…',
        'post_ad' => 'Post Ad',
        'about' => 'About Us',
        'help' => 'Help',
        'login' => 'Login',
        'logout' => 'Logout',
        'register' => 'Register',
        'my_listings' => 'My Listings',
        'admin' => 'Admin',
        'settings' => 'Settings',
        'choose_category' => 'Choose…',
        'city_optional' => 'City (optional)',
        'listing_title' => 'Listing title',
        'listing_body' => 'Listing description',
        'submit_for_review' => 'Submit for review',
        'image_1_optional' => 'Image 1 (optional)',
        'image_2_optional' => 'Image 2 (optional)',
        'nothing_found' => 'Nothing found.',
      ),
    );

    $lang = current_lang();

    if (isset($dict[$lang][$key])) return $dict[$lang][$key];
    if (isset($dict['fa'][$key])) return $dict['fa'][$key];

    return $key;
  }
}

if (!function_exists('get_setting_lang')) {
  function get_setting_lang($baseKey, $default='') {
    if (is_en()) {
      $v = get_setting($baseKey . '_en', '');
      if ($v !== '') return $v;
    }

    return get_setting($baseKey, $default);
  }
}